### PR TITLE
No Answers Fix

### LINKED ISSUE #135: If there's no answers, there should be no followup questions shown
- [ ] don't render the dropdown questions if there's no answers

### PR DESCRIPTION
**Pull request by kevintli**
Resolves #135  

When an answer doesn't exist, avoid trying to display any text or dependent questions (which caused an error previously with the new seed data).

### CODE REVIEW

File: app/javascript/packs/components/DropdownOption.jsx [hunk 1]
```diff
@@ -2,13 +2,16 @@ import React from 'react';
 
 class DropdownOption extends React.Component {
   componentDidMount() {
-    const selected_option_id = this.props.answer.selected_option_id;
-    if (selected_option_id) {
-      this.props.onSelect(selected_option_id);
+    if (this.props.answer) {
+      const selected_option_id = this.props.answer.selected_option_id;
```
Comment (ethanlee16) [inline app/javascript/packs/components/DropdownOption.jsx]: Cool trick;

`const { selected_option_id: selected } = this.props.answer;`

❓

File: app/javascript/packs/components/RangeOption.jsx [hunk 2]
```diff
@@ -12,12 +12,15 @@ class RangeOption extends React.Component {
...
+    if (this.props.answer) {
+      this.checkRange(this.props.answer.text);
+    }
   }
 
   render() {
+    const currentValue = this.props.answer ? this.props.answer.text : "";
     return (<div>
-      <input type="number" defaultValue={this.props.answer.text} onChange={(e) => this.checkRange(e.target.value)} />
+      <input type="number" defaultValue={currentValue} onChange={(e) => this.checkRange(e.target.value)} />
```
Comment (ethanlee16) [inline app/javascript/packs/components/RangeOption.jsx]: when lines get too long maybe add some newlines to your props! can make things look clean, i.e.:

```javascript
<input
     type="number"
     defaultValue={currentValue}
     onChange={(e) => this.checkRange(e.target.value)}
/>
```
