### PR TITLE
Answers: Redux and fetch functions

### LINKED ISSUE #121: Answer create action + reducer
<h1> Redux action for creating an answer </h1>

Resolves #117 

<h3> Fixes </h3>

- [x] Fix fetch function to send proper answer data
- [x] Make answer reducers properly update answer in store
- [x] Temporary answers not working? (_View doesn't update until after we get a fetch response_)
- [ ] React-controlled `RangeOption` should still update even if no dependent option was hit

<h3> Integrate into questionnaire </h3>

- [x] Make OptionsContainer dispatch an action to update answer in store
- [ ] Retry component to submit answer again when fetch request fails

<h3> Actions file </h3>

- [x]  Create Answers actions file

- [x]  Create `current_fetching` answer action
    - type: `IS_FETCHING` and any other parameters necessary for reducer

- [x] Create `update_answer` answer action
    - type: `UPDATE_ANSWER` and answer object to set as params

- [x] Create `done_fetching` answer action
    - inputs dispatch and serialized answer object
    - type: `DONE_FETCHING` and any other parameters necessary for reducer. 

<h3> Reducer file </h3>

- [x] Create Answers reducer file

- [x] Contains a case for `UPDATE_ANSWER`
    - The answer object should be added to the redux store state under the correct building object inside the answers object.

- [x] Contains a case for `IS_FETCHING`
    - when this action is dispatched, redux store state should have a key, value `{ fetching_answer_status: true }`

- [x] Contains a case for `DONE_FETCHING`
    - redux store state should have key `fetching_answer_status` set to `false`

<h3> Constants file </h3>

- [x] Add necessary constants for action type to constants file

<h3> Action file </h3>

- [x] edit_answer action (`PATCH` instead of `POST`)
- [x] create_answer action
    - Inputs dispatch and options for any necessary arguments (i.e. answer parameters)
    - pseudo:

```
createAnswer(dispatch, answer_params={}) {
     dispatch currently_fetching(set_fetching: true)
     await fetch( url='/api/answers/create', body=answer_params).then(
          function(response) { 
               dispatch update_answer(answer_params)
               dispatch done_fetching(set_fetching: false) 
          }
      )
}
```

### PR DESCRIPTION
**Pull request by kevintli**
Resolves #121, #158 

You can now answer questions and see them get updated in store and in the database!!

**Finished**
- Redux actions and reducers to create/edit answers
- Created a requester for `GET`, `DELETE`, `POST`, and `PATCH`

**To be addressed in a later PR**
- Retry component to submit answer again if fetch fails
- React-controlled inputs should update even if no dependent option was hit
- Dispatch action onBlur instead of every time a key is pressed
- **CanCanCan issue:** getting 500 errors when trying to update answers? (these don't show up when we comment out the `load_and_authorize_resource` line)
- More descriptive PropTypes (using shape) once we get Flow working

### CODE REVIEW

File: app/javascript/packs/reducers/buildings.js [hunk 1]
```diff
@@ -78,14 +85,106 @@ function saveBuilding(state, action) {
...
   switch (action.type) {
+    // Buildings
     case ADD_BUILDING: return addBuilding(state, action);
     case EDIT_BUILDING: return editBuilding(state, action);
     case REMOVE_BUILDING: return removeBuilding(state, action);
     case CREATE_BUILDING: return saveBuilding(state, action);
     case UPDATE_BUILDING: return saveBuilding(state, action);
+
+    // Answers
+    case FETCHING_ANSWER: return beforeFetchAnswer(state, action);
```
Comment (ethanlee16) [inline app/javascript/packs/reducers/buildings.js]: One thing we can do to improve this structure is export answers into a separate reducer and respond to that in these answers cases with:

```javascript
default: return {...state, answers: beforeFetchAnswer(state.answers, action) }
```
Let me know what you think!

File: app/javascript/packs/actions/buildings.js [hunk 2]
```diff
@@ -34,6 +34,22 @@ export function removeBuilding(id, dispatch) {
...
+function saveBuilding(type, id, response) {
+  return {
+    type,
+    status: FETCH_SUCCESS,
+    buildingId: id,
+    response
+  };
+}
+
+function saveBuildingError(type, id, error) {
```
[the remark this answers is not in the document]
Comment (kevintli) [reply app/javascript/packs/actions/buildings.js]: I can rename this, but I'm not sure if we're using the buildings actions and reducers anywhere? This function has a call to saveError() which hasn't been defined

[the remark this answers is not in the document]
Comment (ethanlee16) [reply app/javascript/packs/actions/buildings.js]: Even if we're not, let's just set up the structure so that whoever picks this up will start off with the correct naming! Maybe make a `TODO` comment for implementing the `saveError` function or changing `saveError` within the `answers` reducer to a generic error handler function that accepts a `type` field and returns the action object (then it can be reused by other reducers).

File: app/javascript/packs/containers/OptionsContainer.jsx [hunk 3]
```diff
@@ -60,12 +79,26 @@ function mapStateToProps(state, ownProps) {
...
   }
 }
 
+OptionsContainer.propTypes = {
+  question_id: PropTypes.number.isRequired,
+  building_id: PropTypes.number.isRequired,
+  question_type: PropTypes.string.isRequired,
+  options: PropTypes.object.isRequired,
+  dependentQuestions: PropTypes.object.isRequired,
+  answer: PropTypes.object  // Optional - new questions can have no answer
```
[the remark this answers is not in the document]
Comment (kevintli) [reply app/javascript/packs/containers/OptionsContainer.jsx]: Answer has all of these things -- would I have to include all of them in PropTypes?

`{
    "id":7,
    "text":"55",
    "building_id":1,
    "question_id":7,
    "created_at":"2018-03-05T03:36:21.285Z",
    "updated_at":"2018-0305T03:36:21.285Z",
    "selected_option_id":6,
    "attachment_file_name":null,
    "attachment_content_type":null,
    "attachment_file_size":null,
    "attachment_updated_at":null
}`

File: app/javascript/packs/reducers/buildings.js (hunk 1 above)
Comment (kevintli) [reply app/javascript/packs/reducers/buildings.js]: So would the answers reducer get the building object as state instead of the answer object? I thought you meant that the default case would go in the buildings reducer, and it would say something like:

`default: return {...state, answers: answers(state.answers, action) }`

(where `answers()` is the answers reducer itself)

Comment (ethanlee16) [reply app/javascript/packs/reducers/buildings.js]: Yes, this is what I meant!

File: app/javascript/packs/containers/OptionsContainer.jsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (kevintli) [reply app/javascript/packs/containers/OptionsContainer.jsx]: Filing as tech debt -- will address later when we start using Flow

**Comment by kevintli** [comment]
Please review again and I can merge!

File: app/javascript/packs/containers/OptionsContainer.jsx [hunk 4]
```diff
@@ -9,28 +9,34 @@ import Question from '../components/Question';
...
+  /**
+   * Callback for when an option has been triggered. Will update the answer in database and store.
+   *
+   * @param option_id   id of the selected option
+   * @param value       The data of the updated answer. For range options, this is the number the user inputted;
+   *                      for dropdown options, it's the text of the option that was selected.
+   */
+  handleSelect(option_id, value) {
     // Set up answer data to send in fetch request
+    console.log("ANSWER");
```
Comment (ethanlee16) [inline app/javascript/packs/containers/OptionsContainer.jsx]: Do we want to remove these log statements before merging?

Comment (kevintli) [reply app/javascript/packs/containers/OptionsContainer.jsx]: Oh oops! Just removed them

**Comment by ethanlee16** [comment]
@JustinMi :')
